# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
-
  goos:
    - darwin
    - linux
    - windows
  env:
    - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
   name: release-test
   github:
     owner: markbates
     name: homebrew-tap
   homepage: https://gobuffalo.io
   description: me testing releases
   install: |
     bin.install "release-test"
   test: |
     system "#{bin}/release-test"
