builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./main.go
    binary: release-test
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
   name: release-test
   github:
     owner: markbates
     name: homebrew-tap
   homepage: https://gobuffalo.io
   description: me testing releases
   install: |
     bin.install "release-test"
   test: |
     system "#{bin}/release-test"
